CREATE DATABASE [HOO] ON  PRIMARY 
( NAME = N'HOO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL2008\MSSQL\DATA\HOO.mdf' , SIZE = 2048KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HOO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL2008\MSSQL\DATA\HOO_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [HOO] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [HOO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HOO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HOO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HOO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HOO] SET ARITHABORT OFF 
GO
ALTER DATABASE [HOO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HOO] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [HOO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HOO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HOO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HOO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HOO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HOO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HOO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HOO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HOO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HOO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HOO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HOO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HOO] SET  READ_WRITE 
GO
ALTER DATABASE [HOO] SET RECOVERY FULL 
GO
ALTER DATABASE [HOO] SET  MULTI_USER 
GO
ALTER DATABASE [HOO] SET PAGE_VERIFY CHECKSUM  
GO
USE [HOO]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [HOO] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
