// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HOO.WebClient {
	
	
	public partial class PlayerInfoPanel {
		
		protected System.Web.UI.WebControls.Panel pControl;
		
		protected System.Web.UI.WebControls.Panel pInfo;
		
		protected System.Web.UI.WebControls.Literal ltPlayerName;
		
		protected System.Web.UI.WebControls.Literal ltMotto;
		
		protected System.Web.UI.WebControls.Literal ltTotalCredits;
		
		protected System.Web.UI.WebControls.Literal ltCreditsChange;
		
		protected System.Web.UI.WebControls.Panel pLoginRegister;
	}
}
