// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HOO.WebClient {
	
	
	public partial class Register {
		
		protected System.Web.UI.WebControls.Content defBody;
		
		protected System.Web.UI.WebControls.TextBox tbUsername;
		
		protected System.Web.UI.WebControls.TextBox tbPassword;
		
		protected System.Web.UI.WebControls.TextBox tbPassword2;
		
		protected System.Web.UI.WebControls.TextBox tbEmail;
		
		protected System.Web.UI.WebControls.TextBox tbLeaderName;
		
		protected System.Web.UI.WebControls.TextBox tbRace;
		
		protected System.Web.UI.WebControls.TextBox tbMotto;
		
		protected System.Web.UI.WebControls.TextBox tbColor;
		
		protected System.Web.UI.WebControls.Button btnRegister;
	}
}
