// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HOO.WebClient {
	
	
	public partial class StarData {
		
		protected System.Web.UI.WebControls.Content defBody;
		
		protected System.Web.UI.WebControls.Literal ltStarName;
		
		protected System.Web.UI.WebControls.Literal ltStarClass;
		
		protected System.Web.UI.WebControls.Literal ltX;
		
		protected System.Web.UI.WebControls.Literal ltY;
		
		protected System.Web.UI.WebControls.Literal ltZ;
		
		protected System.Web.UI.WebControls.GridView gvNearestStars;
		
		protected System.Web.UI.WebControls.Literal ltXCoo;
		
		protected System.Web.UI.WebControls.Literal ltYCoo;
		
		protected System.Web.UI.WebControls.Literal ltZCoo;
		
		protected System.Web.UI.WebControls.Literal ltDistance;
	}
}
